export const STAGES = {
  POWER_OFF: 0,
  HARDWARE_CALIBRATION: 1,
  RESONANCE: 2,
  HANDSHAKE: 3,
  VIBE_THERMAL_TASK: 4,
  ROUTING_MANUAL: 5,
  ROUTING_AUTO: 6,
  SOFTWARE_FAULT: 7,
  UNLOCKED: 8,
  COMPLETED: 9,
  HOSTILE_LOCKDOWN: 10,
  PURIFIED: 11,
  BOSS_INTRO:      12,
  BOSS_FIGHT:      13,
  FALSE_VICTORY:   14,
  RILEY_UNBOUND:   15,
};

export const VIBE_COLORS = ['#00F0FF', '#FF0055', '#39FF14', '#BC13FE'];
